### ISSUE TITLE
Need help to generate nrfdiscovey server stub

### ISSUE THREAD

**Issue by ramrattle** [attilajak/nrfpysim#1]
Hi @attilajak,

Thanks a lot for putting this repo, it's really really helpful, I created the json for discovery using the following command

java -jar /home/test/swag/swagger-codegen-cli.jar generate -i TS29510_Nnrf_NFDiscovery.yaml -l openapi -o samples/server/nrfopenapi

**but how do I convert the json to python flask server**? I ran the below command but I don't see __init__.py same as yours, can you please share what command you ran to convert generator json to stub server

java -jar /home/test/swag/swagger-codegen-cli.jar generate -i nrfopenapi/openapi.json -l python-flask -o /tmp/test

**Comment by attilajak** [comment]
Hi,

nrfpysim put on github is not auto generated using swagger. I have tried
generating python flask server stub using swagger few times and there were
problems in auto generation of swagger. I have not tried with recent
swagger releases. (generating node.js stubs seemed to be successful for me)

You can't generate json and then create a python flask server out of it.
the command above needs to provide flask as output instead of -l openopi

regds

**Comment by ramrattle** [comment]
Thanks a lot @attilajak for replying, appreciate it, naive question,  does that mean you manually coded the init.py or used any generators? Im confused how those files came, will be helpful if u share the command used to generate these files if any.

**Comment by attilajak** [comment]
yes, it is manually coded. I was not successful in making python flask
generated code to work (Lot of run time issues encountered). swagger is
still not robust enough to process All OpenAPI 3.0 YAML definitions. You
can try generating a python flask stub server using swagger editor itself.

regds
